version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
python:
  install:
    - requirements: docs/requirements.txt
    - path: .
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip
  - epub
