name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.14-dev', python: '3.14-dev', tox: py314}
          - {name: '3.13', python: '3.13', tox: py313}
          - {name: '3.12', python: '3.12', tox: py312}
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: PyPy3, python: 'pypy-3.11', tox: pypy311}
          - {name: Style, python: '3.13', tox: flake8}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox
      - run: tox -v -e ${{ matrix.tox }}
