name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.14-dev', python: '3.14', just: test}
          - {name: '3.13', python: '3.13', just: test}
          - {name: '3.12', python: '3.12', just: test}
          - {name: '3.11', python: '3.11', just: test}
          - {name: '3.10', python: '3.10', just: test}
          - {name: '3.9', python: '3.9', just: test}
          - {name: PyPy3, python: 'pypy3.11', just: test}
          - {name: Lint, python: '3.13', just: lint}
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
      - env:
          UV_PYTHON: ${{ matrix.python }}
        run: uvx --from rust-just just ${{ matrix.just }}
