name: Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.14-dev', tox: py314}
          - {name: '3.13', tox: py313}
          - {name: '3.12', tox: py312}
          - {name: '3.11', tox: py311}
          - {name: '3.10', tox: py310}
          - {name: '3.9', tox: py39}
          - {name: PyPy3, tox: pypy311}
          - {name: Style, tox: flake8}
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
      - run: uvx --with tox-uv tox -v -e ${{ matrix.tox }}
